# Site settings
title: John Businge
email: john.businge@unlv.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://johnxu21.github.io" # the base hostname & protocol for your site
github_username:  johnxu21
linkedin_username: johnxu211
googlescholar: https://scholar.google.com/citations?hl=en&user=b9Kw58UAAAAJ

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"



plugins:
  - jekyll-seo-tag
